title: 'Vent d''est'
default_lang: fr
author:
  name: Grav
  email: joe@test.com
  url: 'http://getgrav.org/'
  gravatar: contact@getgrav.org
  description: 'Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.'
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Vent d''est'
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
blog:
  route: ''
description: 'Blog'
global_featured_image: featured.jpg
social:
  -
    text: facebook
    url: 'https://www.facebook.com/Pure-Music-1739367986287132'
  -
    text: youtube-play
    url: 'https://www.youtube.com/channel/UCiEkoy3KJE18qWgIJ-s_Yuw'
slider:
  -
    image: slide1.jpg
    title: 'Album'
    url: '#'
menu:
copyright: ''
